services:
  rtstt:
    build:
      context: .
      target: gpu # or cpu
    image: rtstt
    container_name: rtstt
    volumes:
      # - ./RealtimeSTT:/app/RealtimeSTT
      # - ./example_browserclient:/app/example_browserclient
      - cache:/root/.cache
    ports:
      - "${RTSTT_PORT:-9050}:9001"

    # if 'gpu' target
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: ["gpu"]
  nginx:
    image: nginx:latest
    container_name: nginx_web
    ports:
      - "${NGINX_PORT:-9051}:80"
    volumes:
      - ./example_browserclient:/usr/share/nginx/html

volumes:
  cache: